[project]
name = "pojtl"
version = "0.1.0"
description = ""
readme = "README.md"
authors = [{ name = "Kisaragi Hiu", email = "mail@kisaragi-hiu.com" }]
requires-python = '>=3.12'
dependencies = [
  "flask>=3.1.2",
  "gunicorn>=23.0.0",
  "kesi>=1.6.0",
]
